### ISSUE TITLE
Food is not working but water yes

### ISSUE THREAD

**Issue by SergioDeoxGames** [MarmotaGit/esx_ladderhud#2]
![image](https://user-images.githubusercontent.com/32938058/55974942-17bc4480-5c89-11e9-8487-c6df7c3d89bb.png)

When i drink the water bar goes up and when i eat, the water goes up. Food never works. Please help.

**Comment by aletato** [comment]
The emty bar isn't water but drunk(alcohol) and "water" is food
![image](https://user-images.githubusercontent.com/23141033/56105885-36e7fa00-5f47-11e9-9929-c186c9a4d641.png)

**Comment by aletato** [comment]
Try to remove esx_drugeffects and "drug" value from status column (**users table**)

**Comment by KilluaZoldyck0099** [comment]
Same... suddently food's bar is empty.
