### ISSUE TITLE
can you tell me to change position?

### ISSUE THREAD

**Issue by SliderKP** [MarmotaGit/esx_ladderhud#6]
how i can change position of bars? because are interposed with inventory

**Comment by lord0o** [comment]
.css file

**Comment by IzITrix** [comment]
after what is the line for change it

**Comment by lord0o** [comment]
> 
> 
> after what is the line for change it

`.container-fluid {
    position: absolute;
    padding: 0;
    margin: 0;
    display: inline-block;
    right: 1.5vw;      <--- here
    bottom: 0;
    transition: right 1.0s;`

**Comment by lord0o** [comment]
`right: 1.5vw;`
